<?xml version="1.0" encoding="utf-8"?>
<!-- DTS2011062005593 renzhanmin 20110621 created -->
<!-- Copyright (C) 2010 The Android Open Source Project

     Licensed under the Apache License, Version 2.0 (the "License");
     you may not use this file except in compliance with the License.
     You may obtain a copy of the License at

          http://www.apache.org/licenses/LICENSE-2.0

     Unless required by applicable law or agreed to in writing, software
     distributed under the License is distributed on an "AS IS" BASIS,
     WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
     See the License for the specific language governing permissions and
     limitations under the License.
-->
<!DOCTYPE MediaSettings [
<!ELEMENT MediaSettings (CamcorderProfiles,
                         EncoderOutputFileFormat+,
                         VideoEncoderCap+,
                         AudioEncoderCap+,
                         VideoDecoderCap,
                         AudioDecoderCap)>
<!ELEMENT CamcorderProfiles (EncoderProfile+, ImageEncoding+, ImageDecoding, Camera)>
<!ELEMENT EncoderProfile (Video, Audio)>
<!ATTLIST EncoderProfile quality (high|low) #REQUIRED>
<!ATTLIST EncoderProfile fileFormat (mp4|3gp) #REQUIRED>
<!ATTLIST EncoderProfile duration (30|60) #REQUIRED>
<!ELEMENT Video EMPTY>
<!ATTLIST Video codec (h264|h263|m4v) #REQUIRED>
<!ATTLIST Video bitRate CDATA #REQUIRED>
<!ATTLIST Video width CDATA #REQUIRED>
<!ATTLIST Video height CDATA #REQUIRED>
<!ATTLIST Video frameRate CDATA #REQUIRED>
<!ELEMENT Audio EMPTY>
<!ATTLIST Audio codec (amrnb|amrwb|aac) #REQUIRED>
<!ATTLIST Audio bitRate CDATA #REQUIRED>
<!ATTLIST Audio sampleRate CDATA #REQUIRED>
<!ATTLIST Audio channels (1|2) #REQUIRED>
<!ELEMENT ImageEncoding EMPTY>
<!ATTLIST ImageEncoding quality (90|80|70|60|50|40) #REQUIRED>
<!ELEMENT ImageDecoding EMPTY>
<!ATTLIST ImageDecoding memCap CDATA #REQUIRED>
<!ELEMENT Camera EMPTY>
<!ATTLIST Camera previewFrameRate CDATA #REQUIRED>
<!ELEMENT EncoderOutputFileFormat EMPTY>
<!ATTLIST EncoderOutputFileFormat name (mp4|3gp) #REQUIRED>
<!ELEMENT VideoEncoderCap EMPTY>
<!ATTLIST VideoEncoderCap name (h264|h263|m4v|wmv) #REQUIRED>
<!ATTLIST VideoEncoderCap enabled (true|false) #REQUIRED>
<!ATTLIST VideoEncoderCap minBitRate CDATA #REQUIRED>
<!ATTLIST VideoEncoderCap maxBitRate CDATA #REQUIRED>
<!ATTLIST VideoEncoderCap minFrameWidth CDATA #REQUIRED>
<!ATTLIST VideoEncoderCap maxFrameWidth CDATA #REQUIRED>
<!ATTLIST VideoEncoderCap minFrameHeight CDATA #REQUIRED>
<!ATTLIST VideoEncoderCap maxFrameHeight CDATA #REQUIRED>
<!ATTLIST VideoEncoderCap minFrameRate CDATA #REQUIRED>
<!ATTLIST VideoEncoderCap maxFrameRate CDATA #REQUIRED>
<!ELEMENT AudioEncoderCap EMPTY>
<!ATTLIST AudioEncoderCap name (amrnb|amrwb|aac|wma) #REQUIRED>
<!ATTLIST AudioEncoderCap enabled (true|false) #REQUIRED>
<!ATTLIST AudioEncoderCap minBitRate CDATA #REQUIRED>
<!ATTLIST AudioEncoderCap maxBitRate CDATA #REQUIRED>
<!ATTLIST AudioEncoderCap minSampleRate CDATA #REQUIRED>
<!ATTLIST AudioEncoderCap maxSampleRate CDATA #REQUIRED>
<!ATTLIST AudioEncoderCap minChannels (1|2) #REQUIRED>
<!ATTLIST AudioEncoderCap maxChannels (1|2) #REQUIRED>
<!ELEMENT VideoDecoderCap EMPTY>
<!ATTLIST VideoDecoderCap name (wmv) #REQUIRED>
<!ATTLIST VideoDecoderCap enabled (true|false) #REQUIRED>
<!ELEMENT AudioDecoderCap EMPTY>
<!ATTLIST AudioDecoderCap name (wma) #REQUIRED>
<!ATTLIST AudioDecoderCap enabled (true|false) #REQUIRED>
]>
<!--
     This file is used to declare the multimedia profiles and capabilities
     on an android-powered device.
-->
<MediaSettings>
    <!-- Each camcorder profile defines a set of predefined configuration parameters -->
    <!-- DTS2011012202331 zhaoxiang 20110122 begin-->
    <CamcorderProfiles cameraId="0">
    <!-- DTS2011012202331 zhaoxiang 20110122 end -->
        <!-- DTS2011011202979 gaoyun 20110111 begin-->
        <!--DTS2011121504793 zhudengkui 20111219 begin-->
        <EncoderProfile quality="720p" fileFormat="mp4" duration="30">
        <!--DTS2011121504793 zhudengkui 20111219 end-->
        <!-- DTS2011011202979 gaoyun 20110111 end -->
	    <!-- DTS2011012202331 zhaoxiang 20110122 begin-->
            <!-- DTS2011091404089 zhudengkui 20110920 begin-->
            <!-- DTS2012040104048 jiangbinghan 20120406 begin-->
            <Video codec="h264"
                   bitRate="8000000"
                   width="1280"
                   height="720"
                   frameRate="30" />
            <!--DTS2012040104048 jiangbinghan 20120406 end-->
            <!-- DTS2011091404089 zhudengkui 20110920 end-->
	    <!-- DTS2011012202331 zhaoxiang 20110122 end -->
            <!-- DTS2012011204739 zhudengkui 20120112 begin-->
            <!-- DTS2012010903786 zhudengkui 20120130 begin-->
            <Audio codec="aac"
                   bitRate="156000"
                   sampleRate="48000"
                   channels="1" />
            <!-- DTS2012010903786 zhudengkui 20120130 end-->
            <!-- DTS2012011204739 zhudengkui 20120112 end-->
        </EncoderProfile>
        <!--DTS2011121504793 zhudengkui 20111219 begin-->
        <EncoderProfile quality="480p" fileFormat="mp4" duration="30">
            <!-- DTS2012010503200 zhudengkui 20120105 begin-->
            <!-- DTS2012040104048 jiangbinghan 20120406 begin-->
            <Video codec="h264"
                   bitRate="5000000"
                   width="640"
                   height="480"
                   frameRate="30" />
            <!--DTS2012040104048 jiangbinghan 20120406 end-->
            <!-- DTS2012010503200 zhudengkui 20120105 end-->
            <!-- DTS2012011204739 zhudengkui 20120112 begin-->
            <!-- DTS2012010903786 zhudengkui 20120130 begin-->
            <Audio codec="aac"
                   bitRate="156000"
                   sampleRate="48000"
                   channels="1" />
            <!-- DTS2012010903786 zhudengkui 20120130 end-->
            <!-- DTS2012011204739 zhudengkui 20120112 end-->
        </EncoderProfile>
        <!--DTS2011121504793 zhudengkui 20111219 end-->
        <!--DTS2012010503200 zhudengkui 20120105 begin-->
        <EncoderProfile quality="qcif" fileFormat="mp4" duration="30">
            <!-- DTS2012040104048 jiangbinghan 20120406 begin-->
            <Video codec="h264"
                   bitRate="192000"
                   width="176"
                   height="144"
                   frameRate="30" />
            <!--DTS2012040104048 jiangbinghan 20120406 end-->
            <Audio codec="amrnb"
                   bitRate="12200"
                   sampleRate="8000"
                   channels="1" />
        </EncoderProfile>
        <!--DTS2012010503200 zhudengkui 20120105 end-->
        <!-- DTS2011011202979 gaoyun 20110111 begin-->
        <EncoderProfile quality="low" fileFormat="mp4" duration="30">
        <!-- DTS2011011202979 gaoyun 20110111 end -->
            <!-- DTS2011121700956 zhudengkui 20111217 begin-->
            <!-- DTS2012040104048 jiangbinghan 20120406 begin-->
            <Video codec="h264"
                   bitRate="192000"
                   width="176"
                   height="144"
                   frameRate="30" />
            <!--DTS2012040104048 jiangbinghan 20120406 end-->
            <!-- DTS2011121700956 zhudengkui 20111217 end-->
            <Audio codec="amrnb"
                   bitRate="12200"
                   sampleRate="8000"
                   channels="1" />

        </EncoderProfile>
        <!--DTS2011121504793 zhudengkui 20111219 begin-->
        <EncoderProfile quality="timelapse720p" fileFormat="mp4" duration="30">
            <!-- DTS2012040104048 jiangbinghan 20120406 begin-->
            <Video codec="h264"
                   bitRate="8000000"
                   width="1280"
                   height="720"
                   frameRate="30" />
            <!--DTS2012040104048 jiangbinghan 20120406 end-->
            <!-- DTS2012011204739 zhudengkui 20120112 begin-->
            <!-- DTS2012010903786 zhudengkui 20120130 begin-->
            <Audio codec="aac"
                   bitRate="156000"
                   sampleRate="48000"
                   channels="1" />
            <!-- DTS2012010903786 zhudengkui 20120130 end-->
            <!-- DTS2012011204739 zhudengkui 20120112 end-->
        </EncoderProfile>

        <EncoderProfile quality="timelapse480p" fileFormat="mp4" duration="30">
            <!-- DTS2012040104048 jiangbinghan 20120406 begin-->
            <Video codec="h264"
                   bitRate="5000000"
                   width="720"
                   height="480"
                   frameRate="30" />
            <!--DTS2012040104048 jiangbinghan 20120406 end-->
            <!-- DTS2012011204739 zhudengkui 20120112 begin-->
            <!-- DTS2012010903786 zhudengkui 20120130 begin-->
            <Audio codec="aac"
                   bitRate="156000"
                   sampleRate="48000"
                   channels="1" />
            <!-- DTS2012010903786 zhudengkui 20120130 end-->
            <!-- DTS2012011204739 zhudengkui 20120112 end-->
        </EncoderProfile>
        <!--DTS2012010503200 zhudengkui 20120105 begin-->
        <EncoderProfile quality="timelapseqcif" fileFormat="mp4" duration="30">
            <!-- DTS2012040104048 jiangbinghan 20120406 begin-->
            <Video codec="h264"
                   bitRate="192000"
                   width="176"
                   height="144"
                   frameRate="30" />
            <!--DTS2012040104048 jiangbinghan 20120406 end-->
            <Audio codec="amrnb"
                   bitRate="12200"
                   sampleRate="8000"
                   channels="1" />
        </EncoderProfile>
        <!--DTS2012010503200 zhudengkui 20120105 end-->
        <EncoderProfile quality="timelapselow" fileFormat="mp4" duration="30">
            <!-- DTS2012040104048 jiangbinghan 20120406 begin-->
            <Video codec="h264"
                   bitRate="192000"
                   width="176"
                   height="144"
                   frameRate="30" />
            <!--DTS2012040104048 jiangbinghan 20120406 end-->
            <Audio codec="amrnb"
                   bitRate="12200"
                   sampleRate="8000"
                   channels="1" />
        </EncoderProfile>
        <!--DTS2011121504793 zhudengkui 20111219 end-->
        <ImageEncoding quality="90" />
        <ImageEncoding quality="80" />
        <ImageEncoding quality="70" />
        <ImageDecoding memCap="20000000" />

        <Camera previewFrameRate="0" />

    </CamcorderProfiles>

    <!-- DTS2011012202331 zhaoxiang 20110122 begin-->
    <CamcorderProfiles cameraId="1">
        <!--DTS2011121504793 zhudengkui 20111219 begin-->
        <!--DTS2012010503200 zhudengkui 20120105 begin-->
        <EncoderProfile quality="480p" fileFormat="mp4" duration="30">
        <!--DTS2011121504793 zhudengkui 20111219 end-->
            <!-- DTS2012040104048 jiangbinghan 20120406 begin-->
            <Video codec="h264"
                   bitRate="5000000"
                   width="640"
                   height="480"
                   frameRate="30" />
            <!--DTS2012040104048 jiangbinghan 20120406 end-->
            <!-- DTS2012011204739 zhudengkui 20120112 begin-->
            <!-- DTS2012010903786 zhudengkui 20120130 begin-->
            <Audio codec="aac"
                   bitRate="156000"
                   sampleRate="48000"
                   channels="1" />
            <!-- DTS2012010903786 zhudengkui 20120130 end-->
            <!-- DTS2012011204739 zhudengkui 20120112 end-->
        </EncoderProfile>
        <!--DTS2012010503200 zhudengkui 20120105 end-->
        <!--DTS2012010503200 zhudengkui 20120105 begin-->
        <EncoderProfile quality="timelapse480p" fileFormat="mp4" duration="30">
        <!--DTS2012010503200 zhudengkui 20120105 end-->
            <!-- DTS2012040104048 jiangbinghan 20120406 begin-->
            <Video codec="h264"
                   bitRate="2000000"
                   width="640"
                   height="480"
                   frameRate="30" />
            <!--DTS2012040104048 jiangbinghan 20120406 end-->
            <!-- DTS2012011204739 zhudengkui 20120112 begin-->
            <!-- DTS2012010903786 zhudengkui 20120130 begin-->
            <Audio codec="aac"
                   bitRate="156000"
                   sampleRate="48000"
                   channels="1" />
            <!-- DTS2012010903786 zhudengkui 20120130 end-->
            <!-- DTS2012011204739 zhudengkui 20120112 end-->
        </EncoderProfile>
        <!--DTS2012010503200 zhudengkui 20120105 begin-->
        <EncoderProfile quality="qcif" fileFormat="mp4" duration="30">
            <!-- DTS2012040104048 jiangbinghan 20120406 begin-->
            <Video codec="h264"
                   bitRate="192000"
                   width="176"
                   height="144"
                   frameRate="30" />
            <!--DTS2012040104048 jiangbinghan 20120406 end-->

            <Audio codec="amrnb"
                   bitRate="12200"
                   sampleRate="8000"
                   channels="1" />

        </EncoderProfile>

        <EncoderProfile quality="timelapseqcif" fileFormat="mp4" duration="30">
            <!-- DTS2012040104048 jiangbinghan 20120406 begin-->
            <Video codec="h264"
                   bitRate="192000"
                   width="176"
                   height="144"
                   frameRate="30" />
            <!--DTS2012040104048 jiangbinghan 20120406 end-->

            <Audio codec="amrnb"
                   bitRate="12200"
                   sampleRate="8000"
                   channels="1" />
        </EncoderProfile>
        <!--DTS2012010503200 zhudengkui 20120105 end-->
        <EncoderProfile quality="low" fileFormat="mp4" duration="30">
            <!-- DTS2011121700956 zhudengkui 20111217 begin-->
            <!-- DTS2012040104048 jiangbinghan 20120406 begin-->
            <Video codec="h264"
                   bitRate="192000"
                   width="176"
                   height="144"
                   frameRate="30" />
            <!--DTS2012040104048 jiangbinghan 20120406 end-->
            <!-- DTS2011121700956 zhudengkui 20111217 end-->
            <Audio codec="amrnb"
                   bitRate="12200"
                   sampleRate="8000"
                   channels="1" />

        </EncoderProfile>
        <!--DTS2011121504793 zhudengkui 20111219 begin-->
        <EncoderProfile quality="timelapselow" fileFormat="mp4" duration="30">
            <!-- DTS2012040104048 jiangbinghan 20120406 begin-->
            <Video codec="h264"
                   bitRate="192000"
                   width="176"
                   height="144"
                   frameRate="30" />
            <!--DTS2012040104048 jiangbinghan 20120406 end-->

            <Audio codec="amrnb"
                   bitRate="12200"
                   sampleRate="8000"
                   channels="1" />
        </EncoderProfile>
        <!--DTS2011121504793 zhudengkui 20111219 end-->
        <ImageEncoding quality="90" />
        <ImageEncoding quality="80" />
        <ImageEncoding quality="70" />
        <ImageDecoding memCap="20000000" />

        <Camera previewFrameRate="0" />

    </CamcorderProfiles>
    <!-- DTS2011012202331 zhaoxiang 20110122 end -->

    <EncoderOutputFileFormat name="3gp" />
    <EncoderOutputFileFormat name="mp4" />

    <!--
         If a codec is not enabled, it is invisible to the applications
         In other words, the applications won't be able to use the codec
         or query the capabilities of the codec at all if it is disabled
    -->
    <!-- DTS2012040104048 jiangbinghan 20120406 begin-->
    <VideoEncoderCap name="h264" enabled="true"
        minBitRate="64000" maxBitRate="20000000"
        minFrameWidth="176" maxFrameWidth="1920"
        minFrameHeight="144" maxFrameHeight="1088"
        minFrameRate="1" maxFrameRate="30" />
    <!--DTS2012040104048 jiangbinghan 20120406 end-->
    <VideoEncoderCap name="h263" enabled="true"
        minBitRate="192000" maxBitRate="2000000"
        minFrameWidth="176" maxFrameWidth="1280"
        minFrameHeight="144" maxFrameHeight="720"
        minFrameRate="1" maxFrameRate="30" />
    <!-- DTS2011091404089 zhudengkui 20110920 begin-->
    <VideoEncoderCap name="m4v" enabled="true"
        minBitRate="192000" maxBitRate="14000000"
        minFrameWidth="176" maxFrameWidth="1280"
        minFrameHeight="144" maxFrameHeight="720"
        minFrameRate="1" maxFrameRate="30" />
    <!-- DTS2011091404089 zhudengkui 20110920 end-->
    <AudioEncoderCap name="amrnb" enabled="true"
        minBitRate="5525" maxBitRate="12200"
        minSampleRate="8000" maxSampleRate="8000"
        minChannels="1" maxChannels="1" />
    <!-- DTS2012011204739 zhudengkui 20120112 begin-->
    <AudioEncoderCap name="aac" enabled="true"
        minBitRate="8000" maxBitRate="156000"
        minSampleRate="8000" maxSampleRate="48000"
        minChannels="1" maxChannels="2" />
    <!-- DTS2012011204739 zhudengkui 20120112 end-->
    <!--
        FIXME:
        We do not check decoder capabilities at present
        At present, we only check whether windows media is visible
        for TEST applications. For other applications, we do
        not perform any checks at all.
    -->
    <VideoDecoderCap name="wmv" enabled="true"/>
    <AudioDecoderCap name="wma" enabled="true"/>
</MediaSettings>
